### ISSUE TITLE
KeyError: 'dev'

### ISSUE THREAD

**Issue by aixiu** [ImYrS/aliyundrive-qr-login#1]
报错了，本地和宝塔上都是一样的错误。
python 版本3.10和3.12 是否和python版本有关？
`/www/server/pyporject_evn/aliyundrive-qr-login_venv/lib/python3.10/site-packages/flask_limiter/extension.py:336: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
warnings.warn(
Traceback (most recent call last):
File "/www/wwwroot/aliyundrive-qr-login/app.py", line 29, in <module>
debug_mode = config['dev'].as_bool('debug')
File "/www/server/pyporject_evn/aliyundrive-qr-login_venv/lib/python3.10/site-packages/configobj/__init__.py", line 554, in __getitem__
val = dict.__getitem__(self, key)
KeyError: 'dev'`

**Comment by ImYrS** [comment]
@aixiu 粘贴 config 配置

**Comment by aixiu** [comment]
@ImYrS 我修改配置文件时把名字改错了，是我大意了。抱歉
